### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by Miamoto-Musashi** [chrisedg87/flutter_rounded_loading_button#20]
when field validation fails the **reset** function raises an error

my code:

```dart
  Future<void> submit() async {
    final allValid = await checkInput();
    if (allValid) {
      Logger.log(tag, message: 'going to submit');
...
      checkImageController.success();
    } else {
      checkImageController.reset();
    }
  }
```

the error

```bash
E/flutter (22565): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
E/flutter (22565): Receiver: null
E/flutter (22565): Tried calling: call()
E/flutter (22565): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (22565): #1      RoundedLoadingButtonController.reset (package:rounded_loading_button/rounded_loading_button.dart:286:19)
E/flutter (22565): #2      OrganizationSignedModel.submit (package:customer/ui/auth/organization_signed_model.dart:118:28)
E/flutter (22565): <asynchronous suspension>
```

this is how I init the controller
```dart
  final RoundedLoadingButtonController checkImageController = RoundedLoadingButtonController();
```

thanks

**Comment by Miamoto-Musashi** [comment]
sorry my fault, wrong controller 🍡
