### ISSUE TITLE
Navigator.of(context)           .pushNamedAndRemoveUntil(LoginScreen.routeName, (route) => false);Unhandled Exception: Bad state: Cannot add new events after calling close

### ISSUE THREAD

**Issue by Abdullahfoysal** [chrisedg87/flutter_rounded_loading_button#48]
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: Bad state: Cannot add new events after calling close
#0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
#1      Subject._add (package:rxdart/src/subjects/subject.dart:141:17)
#2      Subject.add (package:rxdart/src/subjects/subject.dart:135:5)
#3      _StreamSinkWrapper.add (package:rxdart/src/subjects/subject.dart:167:13)
#4      RoundedLoadingButtonState._reset (package:rounded_loading_button/rounded_loading_button.dart:305:17)
<asynchronous suspension>

**Comment by luis-cruzt** [comment]
I'm having the same problem.
